### ISSUE TITLE
Last gomodule release was almost 4 months ago, doesnt have encryption

### ISSUE THREAD

**Issue by mvojacek** [nknorg/nkn-sdk-go#20]
The last tag is v1.1.0-beta9, released on Dec 3. Thats almost 4 months ago. Its doesnt have encryption and compression capabilities.
Maybe its time for a release, so people dont have to circumvent gomod to get new features.

**Comment by yilunzhang** [comment]
That's a good point. We were planning to release a version when the new session mode is tested enough, but I think it's already well tested now

**Comment by yilunzhang** [comment]
Just released v1.2.0. Thanks for suggestion!
