### ISSUE TITLE
Issue running examples

### ISSUE THREAD

**Issue by gesaleh** [nknorg/nkn-sdk-go#3]
**Issue** : enable to run examples
`./client.go:172:15: cannot use dests (type map[string]string) as type []string in argument to c.Send
`
 I did cloned nkn last master release, and nkn-sdk-go but non of the examples run both fails at c.Send 
with error above

**Comment by trueinsider** [comment]
please try latest commit

**Comment by gesaleh** [comment]
thanks did another pull , but now there is another error that i saw before
`./wallet.go:209:48: too many arguments in call to transaction.NewSubscribeTransaction
	have ([]byte, string, string, uint32, uint32, string)
	want ([]byte, string, string, uint32, uint32)
`

**Comment by trueinsider** [comment]
I guess that's because this PR isn't merged yet https://github.com/nknorg/nkn/pull/426

**Comment by trueinsider** [comment]
@gesaleh please try again

**Comment by yilunzhang** [comment]
But you probably need to try it on a cluster with new version instead of release 0.7.3

**Comment by trueinsider** [comment]
if you don't need pubsub then current cluster should be ok
otherwise you can try to use 104.196.247.255:30003 by setting SeedRPCAddr
or wait until testnet is updated to new release

**Comment by trueinsider** [comment]
@gesaleh Testnet was updated, so this should work from the box now. I'm closing this issue, but feel free to open new one if you have any problems.
