### ISSUE TITLE
Make seed node list configurable

### ISSUE THREAD

**Issue by yilunzhang** [nknorg/nkn-sdk-go#4]
It'd useful to be able to configure seed node (list) to connect to, especially for people running node locally.

**Comment by trueinsider** [comment]
You actually can change seed node with `SeedRPCServerAddr` (there is example in README)

**Comment by dreamfly281** [comment]
How about the application pass the seedlist and a parameter to call the SDK, and the seedlist could be set in the configuration of the "application"

**Comment by trueinsider** [comment]
I made `SeedList` public, you can set it before calling `Init()`

**Comment by yilunzhang** [comment]
What do you think of the way that js sdk does it? 
<img width="369" alt="image" src="https://user-images.githubusercontent.com/2791582/52082051-9d689900-2550-11e9-9440-acb97de2d374.png">

**Comment by trueinsider** [comment]
Yes, there is such option from the start. README has example of it.

**Comment by yilunzhang** [comment]
I actually meant to put it as a param/config when calling NewClient because we will need a lot of config in the future. These are the current config on js client apart from public key and identifier, and there will be more in the future. It's better to make the following config per client because even in the same application, we might still want to use different clients for different purposes, e.g. one without packet holding and reply for streaming, and one with holding and reply for message, etc.
<img width="450" alt="image" src="https://user-images.githubusercontent.com/2791582/52082512-d81f0100-2551-11e9-88e9-1e9a3efd861d.png">

**Comment by trueinsider** [comment]
Oh, I see what you mean. Actually, I did it this way, because I couldn't see a use-case of having to connect to different networks (or nodes) from same dApp. If you think otherwise then I'll change it to Client option.

P.S. Packet holding is set per each Send
P.S.2 There is no replies, I believe this logic should be provided on dApp level and SDK instead should have lower possible overhead over sent packets by default.

**Comment by yilunzhang** [comment]
I think the logic is, even if some config is per packet, setting it per client would still be very convenient because it will allow dev to setup a default value for this client. The priority should be per packet setting > client setting > default.

For reply I actually means ACK. The js client will send back an ACK message but it will be optional specified per packet. For streaming or anything that doesn't has to be reliable, it can be turned off. But for message it's very useful.

To be honest I don't see the case that different clients connect to different networks either, but I do see the cases that different client/wallet need different RPC server. For example wallet may want to send txn to a stable enough node, but client may want to spread out the get ws addr request for load balance.

**Comment by trueinsider** [comment]
Since there is no default values in Go it's always per-packet setting.

There is no ack from dest in Go or C# client. It could be provided on top as an option, but js client actually forces one more packet layer on top of base nkn ws layer.

I see, then I'll move seed setting to NewClient.

**Comment by yilunzhang** [comment]
I use this approach to provide a default config, and will be override if some of them are provided by user: https://github.com/nknorg/nnet/blob/master/config/config.go

I agree that we shouldn't force ACK, that's why we should make it optional. But I think it's very useful to provide that option if user wants it to mimic the behavior of TCP to some degree. Actually the proto file contains the definition: https://github.com/nknorg/nkn-client-js/blob/master/lib/protocol/payloads.proto

I think it'd be good to use the same proto file for cross client communication.

**Comment by trueinsider** [comment]
Pushed configs for wallet/client.

Request-Response scheme WIP

**Comment by trueinsider** [comment]
I think this could be closed, because seed node list configuration was done long time ago

And as for req-resp it'll be implemented according to future NKP.
