### ISSUE TITLE
Does not work with `go get` 

### ISSUE THREAD

**Issue by yilunzhang** [nknorg/nkn-sdk-go#5]
I was trying to write compile a piece of go code importing nkn-sdk-go on a fresh debian. What I did is very simple. First install nkn-sdk-go with "go get"

go get github.com/nknorg/nkn-sdk-go

Then compile a simple go project using nkn-sdk-go and get the following error:

../go/src/github.com/nknorg/nkn/common/common.go:15:2: code in directory /home/xxx/go/src/github.com/golang/crypto/ripemd160 expects import "golang.org/x/crypto/ripemd160"
../go/src/github.com/nknorg/gopass/terminal.go:3:8: code in directory /home/xxx/go/src/github.com/golang/crypto/ssh/terminal expects import "golang.org/x/crypto/ssh/terminal"

I don't think it's a problem of nkn-sdk-go but it will definitely affect people trying out nkn-sdk-go since it's the most convenient way to quickly try it out.

**Comment by trueinsider** [comment]
should work now

**Comment by yilunzhang** [comment]
Confirmed working now
